server:
  port: ${PORT:8080}  # Añade esta sección al inicio
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME:sandovaljosearmando69@gmail.com}
    password: ${EMAIL_PASSWORD:crkl ksha bwej cusx}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
        generate_statistics: false
        batch_size: 30
        order_inserts: true
        order_updates: true

  sql:
    init:
      mode: never

  profiles:
    active: prod

security:
  jwt:
    key:
      private: ${JWT_PRIVATE_KEY}
    user:
      generator: AUTH0JWT-BACKEND

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
    info:
      env:
        enabled: true

info:
  app:
    name: api-habbittracker
    version: 2.5
    description: API para seguimiento de habitos
  env:
    profile: ${spring.profiles.active:unknown}